version: '3.8'

services:
  database:
    container_name: music_playlist_db
    image: postgres:14.2-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=musicplaylist
    ports:
      - 15432:5432
    restart: always